name: React Build and Archive

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: VM

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Or whatever version you're using

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Archive
      run: |
        mkdir artifacts
        Compress-Archive -Path build\* -DestinationPath artifacts\reactapp.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: reactapp
        path: artifacts/reactapp.zip
