name: React Build and Archive

on:
  push:
    branches:
      - main  # or your default branch
      - Dev
      - Feature-1
  pull_request:
    branches: [ "main" , "Dev" ]

jobs:
  build:
    runs-on: Windows
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Or whatever version you're using

    - name: Install Dependencies
      run: npm install

    - name: Prepare Analysis Configuration
      shell: cmd
      run: |
        ${{ env.sonarscanner }} begin /k:"ramyam_react" /o:"ramyam" /v:"1.0" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io/"
      env:
        sonarscanner: 'D:\Sonar_Qube\sonarscanner\SonarScanner.MSBuild.exe'

    - name: Build React App
      run: npm run build

    - name: Analysis
      shell: cmd
      run: |
        ${{ env.sonarscanner }} /d:sonar.login="${{ secrets.SONAR_TOKEN }}" end
      env:
        sonarscanner: 'D:\Sonar_Qube\sonarscanner\SonarScanner.MSBuild.exe'

    - name: Archive
      run: |
        mkdir artifacts
        Compress-Archive -Path build\* -DestinationPath artifacts\reactapp.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: reactapp
        path: artifacts/reactapp.zip

  #deploy:
  #  runs-on: VM
  #  needs: build
   # name: Deploy to Azure VM IIS

  #  steps:
  #    - name: Download Artifact
   #     uses: actions/download-artifact@v4
     #   with:
      #    name: reactapp
       #   path: deploy-folder

     # - name: Extract Zip
   #     run: |
     #     Expand-Archive -Path deploy-folder/reactapp.zip -DestinationPath C:\Users\Public\Deploy\React_Deploy -Force

