name: React Build and Archive

on:
  workflow_dispatch:  
  push:
    branches:
      - main  # or your default branch
      - Dev
      - Feature-1
  pull_request:
    branches: [ "main" , "Dev" ]

jobs:
  build:
    runs-on: Windows
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Or whatever version you're using

    - name: Install Dependencies
      run: npm install

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: '17'

    - name: Download and Setup SonarScanner
      run: |
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" -OutFile "sonar-scanner.zip"
          Expand-Archive -Path "sonar-scanner.zip" -DestinationPath "$env:USERPROFILE\sonar-scanner"
          echo "$env:USERPROFILE\sonar-scanner\sonar-scanner-5.0.1.3006-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Run SonarScanner
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
          sonar-scanner.bat `
            -Dsonar.projectKey=ramyam_react ^
            -Dsonar.organization=ramyam ^
            -Dsonar.sources=. ^
            -Dsonar.host.url=https://sonarcloud.io ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} ^
            
            
    - name: Build React App
      run: npm run build


    - name: Archive
      run: |
        mkdir artifacts
        Compress-Archive -Path build\* -DestinationPath artifacts\reactapp.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: reactapp
        path: artifacts/reactapp.zip

  #deploy:
  #  runs-on: VM
  #  needs: build
   # name: Deploy to Azure VM IIS

  #  steps:
  #    - name: Download Artifact
   #     uses: actions/download-artifact@v4
     #   with:
      #    name: reactapp
       #   path: deploy-folder

     # - name: Extract Zip
   #     run: |
     #     Expand-Archive -Path deploy-folder/reactapp.zip -DestinationPath C:\Users\Public\Deploy\React_Deploy -Force

